# Generated by Django 3.2.9 on 2021-11-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='rank',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
